[project]
name = "pycliarr"
version = "0.1.0"
description = "Add a short description here"
authors = ["Vivien Chene <viv.chene@gmail.com>"]
channels = ["conda-forge"]
platforms = ["osx-64"]

[tasks]
build = { cmd = "pip install -e .", cwd = "./" }
radarr = { cmd = ["pycliarr", "-d", "-t", "$RADARR_URL", "-k", "$RADARR_KEY", "radarr"] }
sonarr = { cmd = ["pycliarr", "-d", "-t", "$SONARR_URL", "-k", "$SONARR_KEY", "sonarr"] }
config = { cmd = ["pycliarr", "-t", "", "-k", "", "config"] }
doc = { cmd = ["setup.py", "doc"], cwd = "./" }
test = { cmd = "tox", cwd = "./" }
release = {cmd = ["setup.py", "sdist", "bdist_wheel"], cwd = "./", depends_on = ["test", "doc"]}

[dependencies]
python = ">=3.12.1,<3.13"
requests = ">=2.31.0,<2.32"
m2r2 = ">=0.3.3.post2,<0.3.4"
sphinx = ">=7.2.6,<7.3"
tox = ">=4.11.4,<4.12"
sphinx_rtd_theme = ">=2.0.0,<2.1"
pip = ">=23.3.2,<23.4"
